### ISSUE TITLE
bp_setup_current_user called incorrectly

### ISSUE THREAD

**Issue by Mat2012** [lenasterg/ls_bp_hashtags#12]
Hello, 

Very useful plugin, thanks a lot, @lenasterg !

I have this error notice after activation of the plugin.

Notice: bp_setup_current_user was called incorrectly.
(This message was added in version 1.7.) in /Applications/MAMP/htdocs/mysite/wp-includes/functions.php on line 3560

Do you know how I can fix this ?

Mat

**Comment by lenasterg** [comment]
Fixed
